code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension freakypie.code-python-isort
code --install-extension julialang.language-julia
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension PeterJausovec.vscode-docker
code --install-extension robertohuertasm.vscode-icons
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension vscodevim.vim
code --install-extension wix.vscode-import-cost
code --install-extension yzane.markdown-pdf
