# ====PROMPT-CONFIGURATION====

# Source Powerlevel9k
source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme

# Always show pyenv version
POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true

# Only show Cross on fault, no need for status-code
POWERLEVEL9K_STATUS_CROSS=true

# Left Prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  node_version
  pyenv
  vcs
  status
)

# Right Prompt
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# DIR
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='252'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='238'
POWERLEVEL9K_DIR_HOME_FOREGROUND='252'
POWERLEVEL9K_DIR_HOME_BACKGROUND='238'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='252'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='238'
POWERLEVEL9K_DIR_ETC_FOREGROUND='252'
POWERLEVEL9K_DIR_ETC_BACKGROUND='238'
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='252'
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='238'

POWERLEVEL9K_HOME_ICON='\uf07c' # 
POWERLEVEL9K_HOME_SUB_ICON='\uf07c' # 
POWERLEVEL9K_FOLDER_ICON='\uf07c' # 
POWERLEVEL9K_ETC_ICON='\uf07c' # 

POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true

# NODE_VERISON
POWERLEVEL9K_NODE_VERSION_FOREGROUND='green'
POWERLEVEL9K_NODE_VERSION_BACKGROUND='238'
POWERLEVEL9K_NODE_ICON='\uf898' # 

# PYENV
POWERLEVEL9K_PYENV_FOREGROUND='blue'
POWERLEVEL9K_PYENV_BACKGROUND='238'
POWERLEVEL9K_PYTHON_ICON='\ue606' # 

POWERLEVEL9K_STATUS_OK_FOREGROUND='green'
POWERLEVEL9K_STATUS_OK_BACKGROUND='238'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='238'

# GIT
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='yellow'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='238'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='238'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='238'
