# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="jovial"
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 7

# Plugins
plugins=(
  git
  autojump
  urltools
  bgnotify
  zsh-autosuggestions
  zsh-syntax-highlighting
  jovial
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Path to zsh folder
export ROOT=$HOME/dotfiles/zsh

# Path to dotfiles
export DOTFILES=$HOME/dotfiles

# Path to zsh completion files
export COMPLETIONS=$DOTFILES/zsh/completions

# Path to zsh plugins
export PLUGINS=$DOTFILES/zsh/plugins

# Path to kitty terminal conf
export KITTY_CONFIG_DIRECTORY=$DOTFILES

# Path to bin
export PATH=$PATH:/usr/local/bin

# Path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Path to ssh public key
export SSH_KEY_PATH=$HOME/.ssh/rsa_id

# Export colors
export TERM=xterm-256color

# Export path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Fix brew stuff
export LC_ALL=en_US.UTF-8

# Export GPG
export GPG_TTY=$(tty)

# Klipy
export PATH=$PATH:/Users/smith/.klipy/bin/
alias klipy="/Users/smith/code/oda/klipy/.venv/bin/python -m klipy"

# Spicetify upgrade && spicetify backup apply && spicetify restore backup apply
export PATH=$PATH:/Users/smith/.spicetify

export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

# Fix shit
export LC_CTYPE=C
export LANG=C

# Set Node ENV globally
export NODE_ENV='development'

# History settings
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # Remove older duplicate entries from history
setopt share_history # Remove superfluous blanks from history items
setopt auto_cd # Activating auto cd
zstyle ':completion:*' menu select # Activate highlight on completion

# stuff
export GPF_INSTALL_LOCATION=/usr/local/bin/git-push-fork-to-upstream-branch
export GPF_URL=https://raw.githubusercontent.com/jklukas/git-push-fork-to-upstream-branch/master/git-push-fork-to-upstream-branch
export GPF_USE_SSH=true

# Case-sensitive completion
CASE_SENSITIVE="false"

# Add ssh-agent
ssh-add 2> /dev/null

# Source files
source $ROOT/aliases.zsh
source $ROOT/fzf.zsh
source $ROOT/jovial.zsh

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Eval correct node version on dirchange
eval "$(fnm env --use-on-cd)"

# Poetry path
export PATH="$HOME/.poetry/bin:$PATH"

# Export path to password store
export TIENDA=$HOME/code/oda/tienda

export PATH="/Users/smith/.local/bin:$PATH"

eval $(thefuck --alias)

# Configure direnv
eval "$(direnv hook zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/smith/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/smith/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/smith/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/smith/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
export HOMEBREW_NO_AUTO_UPDATE=true
export PATH="/opt/homebrew/opt/ruby@2.7/bin:$PATH"
