# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to zsh folder
export ROOT=$HOME/dotfiles/zsh

# Path to dotfiles
export DOTFILES=$HOME/dotfiles

# Path to zsh completion files
export COMPLETIONS=$DOTFILES/zsh/completions

# Path to zsh plugins
export PLUGINS=$DOTFILES/zsh/plugins

# Path to kitty terminal conf
export KITTY_CONFIG_DIRECTORY=$DOTFILES

# Path to bin
export PATH=$PATH:/usr/local/bin

# Path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Path to ssh public key
export SSH_KEY_PATH=$HOME/.ssh/rsa_id

# Path to go
export PATH=$HOME/go/bin:$PATH

# Export colors
export TERM=xterm-256color

# Export path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Fix brew stuff
export LC_ALL=en_US.UTF-8

# Export GPG
export GPG_TTY=$(tty)

export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

# Fix pyenv init
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Fix shit
export LC_CTYPE=C
export LANG=C

# Set Node ENV globally
export NODE_ENV='development'

# History settings
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # Remove older duplicate entries from history
setopt share_history # Remove superfluous blanks from history items
setopt auto_cd # Activating auto cd
zstyle ':completion:*' menu select # Activate highlight on completion

# stuff
export GPF_INSTALL_LOCATION=/usr/local/bin/git-push-fork-to-upstream-branch
export GPF_URL=https://raw.githubusercontent.com/jklukas/git-push-fork-to-upstream-branch/master/git-push-fork-to-upstream-branch
export GPF_USE_SSH=true


# Case-sensitive completion
CASE_SENSITIVE="false"

# Add ssh-agent
ssh-add 2> /dev/null

# Source files
source $ROOT/aliases.zsh
source $ROOT/completions.zsh
source $ROOT/plugins.zsh
source $ROOT/fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

export PATH="$HOME/.poetry/bin:$PATH"
