# Path to zsh folder
export ROOT=$HOME/dotfiles/zsh

# Path to dotfiles
export DOTFILES=$HOME/dotfiles

# Path to zsh completion files
export COMPLETIONS=$DOTFILES/zsh/completions

# Path to zsh plugins
export PLUGINS=$DOTFILES/zsh/plugins

# Path to kitty terminal conf
export KITTY_CONFIG_DIRECTORY=$DOTFILES

# Path to bin
export PATH=$PATH:/usr/local/bin

# Path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Path to ssh public key
export SSH_KEY_PATH=$HOME/.ssh/rsa_id

# Export colors
export TERM=xterm-256color

# Export path to password store
export PASSWORD_STORE_DIR=$HOME/.password-store

# Fix brew stuff
export LC_ALL=en_US.UTF-8

# Export GPG
export GPG_TTY=$(tty)

# Klipy
export PATH=$PATH:/Users/smith/.klipy/bin/
alias klipy="/Users/smith/code/oda/klipy/.venv/bin/python -m klipy"

# Spicetify upgrade && spicetify backup apply && spicetify restore backup apply
export PATH=$PATH:/Users/smith/.spicetify

export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

# Fix shit
export LC_CTYPE=C
export LANG=C

# Set Node ENV globally
export NODE_ENV='development'

# History settings
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # Remove older duplicate entries from history
setopt share_history # Remove superfluous blanks from history items
setopt auto_cd # Activating auto cd
zstyle ':completion:*' menu select # Activate highlight on completion

# stuff
export GPF_INSTALL_LOCATION=/usr/local/bin/git-push-fork-to-upstream-branch
export GPF_URL=https://raw.githubusercontent.com/jklukas/git-push-fork-to-upstream-branch/master/git-push-fork-to-upstream-branch
export GPF_USE_SSH=true

# Case-sensitive completion
CASE_SENSITIVE="false"

# Add ssh-agent
ssh-add 2> /dev/null

# Source files
source $ROOT/aliases.zsh
source $ROOT/completions.zsh
source $ROOT/plugins.zsh
source $ROOT/fzf.zsh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(fnm env --use-on-cd)"

# Poetry path
export PATH="$HOME/.poetry/bin:$PATH"

# Configure direnv
eval "$(direnv hook zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/smith/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/smith/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/smith/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/smith/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
